spring.application.name=segurity-service-neumatica
server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-d8vu76e8bjmc738mvoi0-a:5432/bbdd_neumatica_whatsapp
spring.datasource.username=neumatica
spring.datasource.password=RptC4tx9XPHXk0yK9Bi1QQ0x8Hl4IVIz

#spring.datasource.url=jdbc:postgresql://localhost:5432/security_service_neumatica
#spring.datasource.username=postgres
#spring.datasource.password=andres

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.time-zone=America/Bogota

app.jwt.issuer=security-service
app.jwt.secret=CAMBIA_ESTA_CLAVE_POR_UNA_MUY_LARGA_Y_SEGURA
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
app.jwt.private-key=classpath:keys/private.pem
app.jwt.public-key=classpath:keys/public.pem